### ISSUE TITLE
Decawave 1000 device driver source code 

### ISSUE THREAD

**Issue by sarwadenj** [lab11/dw1000-driver#1]
Hi,
I want decawave 1000 device driver source code.
The DW1000 driver source code is targeted for the ARM cortex M3 but is readily portable to other microprocessor systems.
where should i get it.

I'm also seeing your dw1000-driver code can you please add some data about it.

**Comment by colin-broderick** [comment]
I would like the same thing if possible. Where did you originally acquire the source? Would like to use it in one of my own projects but cannot find any license information.

Thanks.

**Comment by ppannuto** [comment]
This is an old project, and I'm going to archive the repository here in a moment. Believe it was an SDK download from an old version of Decawave (now Qorvo)'s website. A more recent iteration of it likely here: https://github.com/Decawave

No license that I know of – this was just some research code published as an artifact aside a paper.
